### PR TITLE
PyCaret

### PR DESCRIPTION
**Pull request by lizababior**
I've added PyCaret node to the pipeline and modified the `requirements.txt`. Please check if it works for you on a clean conda environment

### CODE REVIEW

**Comment by leowajda** [comment]
once all the nodes are in place you can add in the README.md the `kedro` command for running  `pycaret`, I will do the same for `optuna`

**Comment by lizababior** [comment]
Made changes according to your comments. I also saved pycaret model itself just in case.
And let me know, please, when you have a README.md section written for running only `optuna` node. I'll copy and use it. For now I just left there a command to run `pycaret` node.

**Comment by leowajda** [comment]
will check tomorrow, if everything works let's merge this branch before optuna

**Comment by leowajda** [comment]
- [ ] data fed to the model is malformed 
image

- [ ] running `kedro run --nodes=pycaret_predict_ratings` requires the `pycaret_model_input.csv` to be present so it fails on first run, we should instead be using `kedro run --to-outputs "pycaret_model","pycaret_rating_predictions","pycaret_model_metrics"`

- [ ] update README.md

- [ ] maybe instead of `params:pycaret_user_rating` => `params:pycaret_target_column`  ?

**Comment by lizababior** [comment]
I'll keep only movies and ratings tables for PyCaret. Dont see any use of links and tags

**Pull request merged**
